# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py
import numpy as np

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [12]:
print(np.__version__,"\n",np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/a7054/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/a7054/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/a7054/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 

#### 3. Create a null vector of size 10 (★☆☆)

In [13]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [16]:
a = np.zeros((10,10))
print(a.size, a.itemsize)

100 8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [19]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [21]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [22]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [26]:
a = np.arange(10,50)
print(a)
answer(7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [28]:
a = np.arange(10)
print(a)
a = a[::-1]
print(a)
answer(8)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [48]:
a = np.arange(9).reshape(3,3)
print(a)
answer(9)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [66]:
a = np.array([1,2,0,0,4,0])
answer(10)
nz_pos = np.nonzero(a)
print(nz_pos)

nz = np.nonzero([1,2,0,0,4,0])
print(nz)
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [68]:
a = np.eye(3)
print(a)
answer(11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Z = np.eye(3)
print(Z)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [77]:
# 1
a_1 = np.random.rand(3,3,3)
# 2
a_2 = np.random.uniform(0, 1, (3,3,3))
# 3
rng = np.random.default_rng()
a_3 = rng.random((3,3,3))
print(a_1)
answer(12)

[[[0.73681906 0.25023429 0.79400995]
  [0.25810551 0.62399053 0.66080732]
  [0.93791938 0.44343633 0.50219135]]

 [[0.57966181 0.70212011 0.64707917]
  [0.96668386 0.53878237 0.91385037]
  [0.18745039 0.40896305 0.9969612 ]]

 [[0.92965785 0.8617908  0.76067401]
  [0.35802269 0.92052067 0.15966413]
  [0.66950814 0.56033162 0.05985607]]]
Z = np.random.random((3,3,3))
print(Z)


In [79]:
print(np.random.random.__doc__)


        random(size=None)

        Return random floats in the half-open interval [0.0, 1.0). Alias for
        `random_sample` to ease forward-porting to the new random API.
        


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [139]:
a = np.random.rand(10,10)
min_pos_array = a.argmin()
[x, y] = np.indices((10,10))
x, y = x.flatten(), y.flatten()
# print(min_pos)
min_pos = (x[min_pos_array], y[min_pos_array])
print("find indices: ", min_pos_array, min_pos)
answer(13)
amin, amax = a.min(), a.max()
print("find values: ", amin, amax)

find indices:  49 (4, 9)
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
find values:  0.006376298136334668 0.999927344001663


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [141]:
a = np.random.random(30)
aavg = a.mean()
answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [150]:
# 1
def border2d(ashape):
    nashape = np.array(ashape)
    nashape -= 2
    zero_core = np.zeros(nashape)
    return np.pad(zero_core, 1, constant_values = 1)
border2d((9,13))
# 2
a = np.ones((10,10))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [151]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan # np.nan
np.nan == np.nan # False
np.inf > np.nan # False
np.nan - np.nan # nan
np.nan in set([np.nan]) # True
0.3 == 3 * 0.1 #False
```

nan

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [28]:
# a = np.diag([1,2,3,4])
# np.pad(a, ((1, 0), (0, 1)))

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [27]:
answer(18)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [35]:
a = np.zeros((8, 8))
a[::2, ::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [31]:
answer(19)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [39]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


In [4]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [7]:
a = np.array([[1, 0], [0, 1]])
b = np.tile(a, (4, 4))
print(b)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [12]:
a = np.random.rand(5, 5)
a_i = (a - a.mean()) / a.std()
print(a_i)

[[-0.53825339  1.0223549   0.68300879  0.1778718   1.09117613]
 [-2.37887565  1.07003915 -1.19447464  0.72410655 -0.80430317]
 [ 0.92273399 -0.21265252  0.08585317 -1.0735898   1.11236083]
 [ 0.82133563  0.96290228 -0.40211043  0.85999139 -1.40222284]
 [-1.19155632  1.16422405 -0.36253721 -1.36163015  0.22424747]]


In [19]:
a = np.diag([1, 2, 3, 4, 5])
a_i_all = (a - a.mean()) / a.std()
a_i_row = (a - a.mean(axis = 0)) / a.std(axis = 0)
print(a_i_all, a_i_row,sep='\n')

[[ 0.29488391 -0.44232587 -0.44232587 -0.44232587 -0.44232587]
 [-0.44232587  1.03209369 -0.44232587 -0.44232587 -0.44232587]
 [-0.44232587 -0.44232587  1.76930347 -0.44232587 -0.44232587]
 [-0.44232587 -0.44232587 -0.44232587  2.50651325 -0.44232587]
 [-0.44232587 -0.44232587 -0.44232587 -0.44232587  3.24372304]]
[[ 2.  -0.5 -0.5 -0.5 -0.5]
 [-0.5  2.  -0.5 -0.5 -0.5]
 [-0.5 -0.5  2.  -0.5 -0.5]
 [-0.5 -0.5 -0.5  2.  -0.5]
 [-0.5 -0.5 -0.5 -0.5  2. ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [21]:
answer(23)
color = np.dtype([("r", np.ubyte),
                 ("g", np.ubyte),
                 ("b", np.ubyte),
                 ("a", np.ubyte)])

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
a = np.random.randint(1, 9, (5, 3))
b = np.random.randint(1, 9, (3, 2))
c = a @ b
print(a, b, c, sep = "\n")
print(answer(24))

[[6 3 8]
 [1 5 2]
 [7 2 5]
 [2 3 5]
 [1 6 7]]
[[5 7]
 [6 1]
 [5 4]]
[[88 77]
 [45 20]
 [72 71]
 [53 37]
 [76 41]]
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)
None


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [46]:
a = np.random.randint(0, 20, 20)
a[(a>3) & (a<8)] *= -1
print(a)


[-5  1 11 17  3 15  1 18 14 -4  1 -7  2 -5  0 19 -6 16 17  1]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [14]:
print(np.sum(range(5), -1))
print(sum(range(5), -1))

10
9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [44]:
a = np.arange(10)
print(a, a < -a, a**a, 2 << a >>2, 1j * a, a/1/1,  sep='\n')
answer(27)

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False False False False False]
[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [63]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\a7054\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\a7054\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [71]:
a = np.random.uniform(-10,10,10)
print(a)
print(np.where(a>0, np.ceil(a), np.floor(a)))
print(answer(29))

[ 3.61877036 -4.77610207  0.56224069  2.37150546 -9.59651964  2.6466543
 -1.3409542   2.18596098 -7.869042    1.66208152]
[  4.  -5.   1.   3. -10.   3.  -2.   3.  -8.   2.]
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))
None


#### 30. How to find common values between two arrays? (★☆☆)

In [83]:
a = np.random.randint(-5, 5, 10)
b = np.random.randint(-5, 5, 10)

print(a, b, np.intersect1d(a, b), sep = "\n")

print(answer(30))

[ 1  0 -2 -3  4 -4  4  0  0  3]
[ 1  1  1  0 -5  1  2  3  0 -2]
[-2  0  1  3]
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))
None


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [124]:
# print(answer(31))

print(np.seterr.__doc__)
Z = np.ones(1) / 0
b = np.arange(3) / 0
_ = np.seterr(**defaults)

with np.errstate(all = 'ignore'):
    np.arange(3) / 0
    
# print(Z, b)


    Set how floating-point errors are handled.

    Note that operations on integer scalar types (such as `int16`) are
    handled like floating point, and are affected by these settings.

    Parameters
    ----------
    all : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
        Set treatment for all types of floating-point errors at once:

        - ignore: Take no action when the exception occurs.
        - warn: Print a `RuntimeWarning` (via the Python `warnings` module).
        - raise: Raise a `FloatingPointError`.
        - call: Call a function specified using the `seterrcall` function.
        - print: Print a warning directly to ``stdout``.
        - log: Record error in a Log object specified by `seterrcall`.

        The default is not to change the current behavior.
    divide : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
        Treatment for division by zero.
    over : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
  

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [128]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [24]:
"""
The use of dtype datetime64 & timedelta64
"""

date_of_today = np.datetime64("today")
date_of_yesterday = date_of_today - np.timedelta64(1, "D")
date_of_tomorrow = date_of_today + np.timedelta64(1, "D")
print(date_of_today, date_of_yesterday, date_of_tomorrow, sep = "\n")
print(np.dtype(np.timedelta64(1, "D")))

2021-07-16
2021-07-15
2021-07-17
timedelta64[D]


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
"""
Combination of datetime64 and arange
"""

print(np.arange(np.datetime64("2016-07"), np.datetime64("2016-08"), dtype = "datetime64[D]"))
# or
print(np.arange(np.datetime64("2016-07-01"), np.datetime64("2016-08-01")))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [37]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


In [47]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A, B, out=B)
np.add(A, B, out=B)
np.add(A, B, out=B)
np.add(A, B, out=B)
np.add(A, B, out=B)
np.add(A, B, out=B)
print(B)

[8. 8. 8.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [53]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


In [58]:
a = np.random.uniform(0, 9, 10)
def Way1(a):
    return a // 1

def Way2(a):
    return np.floor(a)

def Way3(a):
    return a.astype("int")

def Way4(a):
    return np.trunc(a)
    

print(a, Way1(a), Way2(a), Way3(a), Way4(a), sep="\n")

[3.54051474 1.04075693 7.48109414 0.33319235 8.06537531 5.00253048
 4.5655261  6.46269148 2.73424067 1.44824931]
[3. 1. 7. 0. 8. 5. 4. 6. 2. 1.]
[3. 1. 7. 0. 8. 5. 4. 6. 2. 1.]
[3 1 7 0 8 5 4 6 2 1]
[3. 1. 7. 0. 8. 5. 4. 6. 2. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [86]:
a = np.arange(5).repeat(5).reshape((5,5)).T
a = np.tile(np.arange(5), (5,1)) # without using boardcast
a = np.zeros((5,5)) + np.arange(5) # using boardcast
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [93]:
"""
the use of np.fromiter
which means create an array from an iterable object

np.fromiter(iter, dtype, count = -1, like=None):
Para:
    iter: iterable object
    dtype: data-type of the returned array
    count: The number of items from iterable. The default is -1, which means all data is read
"""

def generate():
    for x in range(100):
        yield x
        
a = np.fromiter(generate(), dtype = int, count = 20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [95]:
a = np.linspace(0,1, 11, endpoint = False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [98]:
a = np.random.rand(10)
a = np.sort(a)
print(answer(40))

Z = np.random.random(10)
Z.sort()
print(Z)
None


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [101]:
answer(41)

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)


In [126]:
from time import time

a = np.arange(10000000)
begin_1 = time()
np.sum(a)
end_1 = time()
print(end_1 - begin_1)

begin_2 = time()
np.add.reduce(a)
end_2 = time()
print(end_2 - begin_2)


0.004990816116333008
0.005457878112792969


#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)